Translations feature in tools web
makerspacelt/tools pull request #14
Opened 2022-01-12 18:50 UTC by domasV

Enabled default Symfony translations;
Translated web texts;
Provided (Google translate) translated Lithuanian texts.

2022-01-12 19:57 UTC, aivarasbaranauskas requested changes
Translation tags are missing in some places.

2022-01-13 06:33 UTC, aivarasbaranauskas requested changes
The branch is behind the 'develop' branch and there is a merge conflict. Please do a rebase and solve the conflict.

2022-01-19 17:35 UTC, domasV commented
Done, please review and merge.

2022-01-19 17:39 UTC, aivarasbaranauskas approved these changes

2022-01-19 17:39 UTC, merged