Reactive tools search with JS
makerspacelt/tools pull request #31
Opened 2022-03-16 18:40 UTC by domasV

2022-03-24 15:12 UTC, aivarasbaranauskas requested changes

2022-03-24 15:12 UTC, aivarasbaranauskas commented on src/Controller/ApiController.php
> +    }
Unused method, should be removed.

2022-04-06 17:26 UTC, domasV commented on src/Controller/ApiController.php
> +    }
Removed

2022-04-06 17:27 UTC, domasV commented on public/js/tool-search.js
> +        searchString.addEventListener('keyup', searchTools)
Added delay with variable. Variable set for 1 second, which feels natural, might need to fine-tune according more opinions :D

2022-04-07 05:38 UTC, aivarasbaranauskas requested changes

2022-04-07 05:38 UTC, aivarasbaranauskas commented on public/js/tool-search.js
> +        searchString.addEventListener('keyup', searchTools)
Debounce feel buggy, if I type something in a 1s window after last time search was done it does not trigger new search later.

I would rather have used setTimeout() than calculating intervals manually. A good example: https://www.freecodecamp.org/news/javascript-debounce-example

2022-04-07 16:36 UTC, domasV commented on public/js/tool-search.js
> +        searchString.addEventListener('keyup', searchTools)
Agree. Changed to the provided debounce algorithm.

2022-04-08 07:16 UTC, aivarasbaranauskas approved these changes

2022-04-08 07:16 UTC, merged